### ISSUE TITLE
Ensemble: keep_rows() error. Dropped rows "not found."

### ISSUE THREAD

**Issue by wkitlasten** [jtwhite79/pestpp#6]
The best lambda from the subset evaluation has two dropped realizations:

  ```
---  droppping realizations as bad:  2  ---  
...dropping par:obs realizations: 857 : 853 , 886 : 884 , 

  ---  phi summary for lambda, scale fac:2e+12 , 0.7 ,   ---  
       phi type           mean            std            min            max
      composite    4.06042e+13    2.96252e+13    1.92525e+13    1.36628e+14
       measured    4.06042e+13    2.96252e+13    1.92525e+13    1.36628e+14
 regularization          52.82        65.3603              0         240.52
         actual    4.06042e+13    2.96251e+13    1.92525e+13    1.36628e+14
     current reg_factor: 0
```

Trying to run the remaining realizations results in the following error:

```
Error condition prevents further execution:
Ensemble Error: Ensemble::keep_rows() error: the following real names not found: 857,886,
```
Using ipestpp-ies downloaded on 8/30/2014

**Comment by jtwhite79** [comment]
So much for "unrelated" issues in #7  - the issues with that test that was failing turned out to be directly related to this issue.  So I added a few new secret options for debugging to simulate run fails and bad phi drops and I could only trigger this issue if iter > 1 with at least one subset run fail and at least one bad phi drop on the subset also - that is a serious bug @wkitlasten! Most of the trouble is related to allowing separate realization names for the obs and par ensembles combined with the ``subset_how`` support.  So I reworked some of that and it seems to be working (at least test are passing).  I'm considering adding a ``strict_naming`` option to enforce alignment between par and obs realization names - If you generate your ensembles with ``pyemu`` or allow ``pestpp-ies`` to generate them, then the names should always be the same.  The patch (version 4.1.7) has been merged in to develop and master
